name: Build Jeff API Python Package

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    
    - name: Set VAR_VERSION
      run: echo "VAR_VERSION=$(grep '^version' jeff-api/pyproject.toml | head -n 1 | cut -d '"' -f 2)" >> $GITHUB_ENV
            
    - name: Test VAR_VERSION
      run: echo $VAR_VERSION

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build package
      working-directory: ./jeff-api
      run: python -m build
      
    - uses: actions/upload-artifact@v2
      with:
        name: jeff_api-${{env.VAR_VERSION}}-py3-none-any.whl
        path: jeff-api/dist/jeff_api-${{env.VAR_VERSION}}-py3-none-any.whl
        
    - uses: actions/upload-artifact@v2
      with:
        name: jeff_api-${{env.VAR_VERSION}}.tar.gz
        path: jeff-api/dist/jeff_api-${{env.VAR_VERSION}}.tar.gz
